# -*- coding: utf-8 -*-
"""Algoritmo4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12aKY7C-aV6qVU1fFUXSNYrG51Afek4Ij
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
!pip install igraph

import igraph as ig
import matplotlib.pyplot as plt

# Esqueleto

# Debe existir un grafo G, el cual en los nodos tenga como atributo "color", para poder hacer un cambio cuando sea necesario
# Como el siguiente:
n_vertices = 3
edges = [(0, 1), (0, 2), (1, 2), (0, 3), (3, 4), (3, 5), (4, 5)]
g = ig.Graph(n_vertices, edges)

# Set attributes for the graph, nodes, and edges
g["title"] = "Small Social Network"
g.vs["color"] = ["white", "white", "white", "white", "white"]

fig, ax = plt.subplots(figsize=(5,5))
ig.plot(
    g,
    target=ax,
    layout="circle", # print nodes in a circular layout
    vertex_size=0.35,
    vertex_color=[color for color in g.vs["color"]],
    vertex_frame_width=2.0,
    vertex_frame_color="black",
    vertex_label=g.vs["color"],
    vertex_label_size=7.0,
    edge_width=[2],
    edge_color=["#7142cf"]
)

# Se transforma de un Demand Graph a un Colored Graph
def coloredGraph(G):
    # Si v (vertices de G) tiene ns(v) supply nodes, existen ns(v) copias en G˜1
    # cada copia tiene un color con el cual identificar un supply node

    # Si vi y vj (vertices de G) estan conectados por una arista, entonces todas las copias de vi estan conectadas a todas las copias de vj en G˜1 
    pass


# Se
def minimunColor(G):
    # Se construte un nuevo grafo G´ a partir de G de la siguiente forma, dejar todos los nodos del color i en un único nodo V_i
    # Conectar u_i y u_j si y solo si hay al menos una arista entre V_i y V_j.
    # Conectar s´ a u_i, si s está conectado a V_i, y conectar t´ a u_i, si t está conectado a V_i.

    # Computar el mínimo nodo s´t´ en G´, en donde cada nodo debe tener un color distinto.
    # El nodo st minimo color en G es dado por los colores de los cut nodes s´t´ en G´.

    

    pass