# -*- coding: utf-8 -*-
"""Algoritmo6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbyeZ02ydfzjhBo0Hv1zNXgeHKG-vUqH
"""

# Esqueleto

# Optimal Resource Computation
# 
 
def OPT_ALLOC(a,Ga,Gb,b,Dth):
    p1 = 0
    p2 = max(size(Ga), size(Gb))
    D = inf
    while D > Dth:
        v = (p1+p2)/p2
        ˜b =  E B(al,v) # Sumatoria
        if ˜b > b:
            p2 = v
        else:
            p1 = v
        D = |˜b - b|
    xl = EB(al,v)
    return xl, ∀l